[package]
name = "algerflow_guessing_game"
license = "MIT"
description = "A fun game where you guess what number the computer has chosen."
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"